In [1]:
import pandas as pd
import datetime
from tqdm.notebook import tqdm # To display status bar
import snscrape.modules.twitter as sntwitter # To scrape tweets

In [2]:
# Query
cp_query = "canada post"             # keyword
# query = "#canadapost"      # hashtag
# query = "@canadapostcorp"     # mention

# Language
language = "en"

cp_scraper = sntwitter.TwitterSearchScraper(cp_query + " lang:" + language)

In [3]:
cp_tweets = []
cp_tweet_count = 15000

for i, tweet in tqdm(enumerate(cp_scraper.get_items()), total = cp_tweet_count + 1):
    data = [
        tweet.date, 
        tweet.id, 
        tweet.rawContent, 
        tweet.user.username, 
        tweet.likeCount, 
        tweet.retweetCount ]
    
    cp_tweets.append(data)
    if i >= cp_tweet_count:
        break

  0%|          | 0/15001 [00:00<?, ?it/s]

Unavailable user in card on tweet 1658132437833072644
Unavailable user in card on tweet 1658132437833072644
User 1150370223209324545 not found in user refs in card on tweet 1658132437833072644
User 1150370223209324545 not found in user refs in card on tweet 1658132437833072644
Could not translate t.co card URL on tweet 1655243904663298048
Stopping after 20 empty pages

In [5]:
cp_tweet_df = pd.DataFrame(cp_tweets,  columns = ['date', 'id', 'content', 'username', 'like_count', 'retweet_count'])

In [6]:
cp_tweet_df.to_csv('twitter_data.csv', index=False)

In [7]:
cp_tweet_df

,date,id,content,username,like_count,retweet_count
0,2023-06-06 20:39:01+00:00,1666182930425585664,"@KirkLubimov That’s Weimar Canada, post-nation...",DariusXCVI,0,0
1,2023-06-06 20:24:34+00:00,1666179294689624066,"@ottawabluesfest I paid 12$ Canada Post, as we...",Gayytie,0,0
2,2023-06-06 20:06:02+00:00,1666174630728544266,"Canada Post Stamp, 2011, Zodic Rabbit, Animal ...",elda16a,0,0
3,2023-06-06 19:12:03+00:00,1666161043150630918,This arrived on time today!! \nThank you Canad...,ginya97,0,0
4,2023-06-06 19:00:06+00:00,1666158039391404040,@sp00ky20 @canadapostcorp Hi - please send us ...,canadaposthelps,1,0
...,...,...,...,...,...,...
4855,2023-02-16 18:34:17+00:00,1626288876955512832,@MahDryBread Canada Post lose any more of your...,forbiddenspell2,1,0
4856,2023-02-16 18:06:34+00:00,1626281899319787522,Home sales in Canada post worst start to the y...,VernonNews,0,0
4857,2023-02-16 18:04:33+00:00,1626281393398636544,Home sales in Canada post worst start to the y...,SurreyNowLeader,0,0
4858,2023-02-16 18:04:27+00:00,1626281368136331265,@mishiikenhkwe Canada post is sooooo expensive...,Photochickee,1,0
4859,2023-02-16 17:59:20+00:00,1626280081587830785,"@just_nanny Canada Post is all we have nearby,...",mishiikenhkwe,1,0

In [8]:
# Query
pi_query = "purolator"             # keyword
# query = "#purolator"      # hashtag
# query = "@PurolatorInc"     # mention

# Language
language = "en"

pi_scraper = sntwitter.TwitterSearchScraper(pi_query + " lang:" + language)

In [9]:
pi_tweets = []
pi_tweet_count = 15000

for i, tweet in tqdm(enumerate(pi_scraper.get_items()), total = pi_tweet_count + 1):
    data = [
        tweet.date, 
        tweet.id, 
        tweet.rawContent, 
        tweet.user.username, 
        tweet.likeCount, 
        tweet.retweetCount ]
    
    pi_tweets.append(data)
    if i >= pi_tweet_count:
        break

  0%|          | 0/15001 [00:00<?, ?it/s]

Skipping unrecognised entry ID: 'promoted-tweet-1635745952265805829-942ad285ce21e52'
Skipping unrecognised entry ID: 'promoted-tweet-1663929577352339456-94200b3f4fb04fd'
Skipping unrecognised entry ID: 'promoted-tweet-1522348782100254720-94216cc6423d444'
Skipping unrecognised entry ID: 'promoted-tweet-1635745952265805829-942579efd37117a'
Skipping unrecognised entry ID: 'promoted-tweet-1663929577352339456-942e6f8a2b42c3f'
Skipping unrecognised entry ID: 'promoted-tweet-1522348782100254720-942c5cdb758301c'
Skipping unrecognised entry ID: 'promoted-tweet-1635745952265805829-9423f831ea18c80'
Skipping unrecognised entry ID: 'promoted-tweet-1663929577352339456-942a54ff01ca530'
Skipping unrecognised entry ID: 'promoted-tweet-1522348866632249344-9428c5c8d9545c7'
Skipping unrecognised entry ID: 'promoted-tweet-1635745952265805829-9427514e092cd0a'
Skipping unrecognised entry ID: 'promoted-tweet-1663929577352339456-94299fee82150b1'
Skipping unrecognised entry ID: 'promoted-tweet-1522348782100254720-942422f339fb7a1'
Skipping unrecognised entry ID: 'promoted-tweet-1635745952265805829-9422d5cf13d2728'
Skipping unrecognised entry ID: 'promoted-tweet-1665802638724591616-942a19311656c38'
Skipping unrecognised entry ID: 'promoted-tweet-1663929577352339456-9423f38a817578b'
Skipping unrecognised entry ID: 'promoted-tweet-1635745952265805829-9427a0e1fa98348'
Skipping unrecognised entry ID: 'promoted-tweet-1663929577352339456-94273e4740246d7'
Skipping unrecognised entry ID: 'promoted-tweet-1522348782100254720-94281b7c8793ce4'
Skipping unrecognised entry ID: 'promoted-tweet-1635745952265805829-9421d96b0e6c5e9'
Skipping unrecognised entry ID: 'promoted-tweet-1522348782100254720-9425c9118b7da49'
Skipping unrecognised entry ID: 'promoted-tweet-1663929577352339456-9423dbb798db63b'
Skipping unrecognised entry ID: 'promoted-tweet-1635745952265805829-94237e434f78ed8'
Skipping unrecognised entry ID: 'promoted-tweet-1663929577352339456-9424e25fc49600c'
Skipping unrecognised entry ID: 'promoted-tweet-1522348866632249344-94240baed4a6387'
Stopping after 20 empty pages

In [10]:
pi_tweet_df = pd.DataFrame(pi_tweets,  columns = ['date', 'id', 'content', 'username', 'like_count', 'retweet_count'])

In [11]:
pi_tweet_df.to_csv('purolator_data.csv', index=False)

In [12]:
pi_tweet_df

,date,id,content,username,like_count,retweet_count
0,2023-06-06 20:03:48+00:00,1666174066829533185,Dear @Dyson the products are cool but the cust...,LauraLeigh19,0,0
1,2023-06-06 19:40:18+00:00,1666168155138318336,"@CrtclSprnkls Hi Krista, we'll contact the dep...",PurolatorHelp,0,0
2,2023-06-06 19:38:41+00:00,1666167748626399234,"@lieu_days Hi Lu, we're sorry to hear about th...",PurolatorHelp,0,0
3,2023-06-06 17:05:01+00:00,1666129074887045145,"@FnxAu_streams Hello, our sincere apologies. C...",PurolatorHelp,0,0
4,2023-06-06 17:03:17+00:00,1666128638809452557,Sitting at home with the door open and @Purola...,FnxAu_streams,0,0
...,...,...,...,...,...,...
137,2023-05-27 22:16:20+00:00,1662583544311414785,🌊 Joining hands for cleaner lakefronts! 🚮 \n\...,PurolatorInc,2,1
138,2023-05-27 21:06:39+00:00,1662566005271564288,@M777Monroe @BrainardRichard @JimHawk67327371 ...,GMEMDBABY,0,0
139,2023-05-27 19:28:55+00:00,1662541409684017152,My initial purchase is scheduled for delivery ...,rrcool53,0,0
140,2023-05-26 23:10:55+00:00,1662234890912366602,Purolator company from Canada didn't send me t...,KyidaSaBC,0,0
141,2023-05-26 23:10:46+00:00,1662234851884318721,Purolator company from Canada didn't send me t...,KyidaSaBC,0,0

In [13]:
# Query
ups_query = "ups canada"             # keyword
# query = "#upscanada"      # hashtag
# query = "@ups_Canada"     # mention

# Language
language = "en"

ups_scraper = sntwitter.TwitterSearchScraper(ups_query + " lang:" + language)

In [14]:
ups_tweets = []
ups_tweet_count = 15000

for i, tweet in tqdm(enumerate(ups_scraper.get_items()), total = ups_tweet_count + 1):
    data = [
        tweet.date, 
        tweet.id, 
        tweet.rawContent, 
        tweet.user.username, 
        tweet.likeCount, 
        tweet.retweetCount ]
    
    ups_tweets.append(data)
    if i >= ups_tweet_count:
        break

  0%|          | 0/15001 [00:00<?, ?it/s]

Could not translate t.co card URL on tweet 1636372586534932484
Unavailable user in card on tweet 1585183296329236482
Unavailable user in card on tweet 1585183296329236482
User 1293465421589315584 not found in user refs in card on tweet 1585183296329236482
User 1293465421589315584 not found in user refs in card on tweet 1585183296329236482
Unavailable user in card on tweet 1585183256961552385
Unavailable user in card on tweet 1585183256961552385
User 1293465421589315584 not found in user refs in card on tweet 1585183256961552385
User 1293465421589315584 not found in user refs in card on tweet 1585183256961552385
Stopping after 20 empty pages

In [15]:
ups_tweet_df = pd.DataFrame(ups_tweets,  columns = ['date', 'id', 'content', 'username', 'like_count', 'retweet_count'])

In [16]:
ups_tweet_df.to_csv('ups_data.csv', index=False)

In [17]:
ups_tweet_df

,date,id,content,username,like_count,retweet_count
0,2023-06-06 19:39:47+00:00,1666168023336534016,@ErinInTheMorn “Medical authority” (only in th...,AwakeBPS,0,0
1,2023-06-06 19:38:45+00:00,1666167764392763393,Our 2023 🌳🍎☀️WELLNESS WALK️ ☀️🍎🌳 was a huge hi...,TFSS_,0,0
2,2023-06-06 19:33:01+00:00,1666166320826572804,"@mark_shteinberg Hello, we are truly sorry for...",UPS_Canada,0,0
3,2023-06-06 19:26:13+00:00,1666164611538735109,@HatTrickREI @UPS Same here in the great South...,rogerms12,1,0
4,2023-06-06 18:54:59+00:00,1666156751404531719,@TheNamibian #harmony World 🌍 futuristic Julia...,JuliaMe68293271,0,0
...,...,...,...,...,...,...
9994,2022-06-21 19:43:49+00:00,1539333287231078400,@UPS @UPS_Canada is just SUCH a scummy company...,PirateHempress,0,0
9995,2022-06-21 18:09:52+00:00,1539309643448606720,@UPS It's not about being sorry for the packag...,AttilaVinczer,0,0
9996,2022-06-21 18:04:31+00:00,1539308297681276928,On June 15&amp;16 Village staff planted trees ...,VLGNewMaryland,1,0
9997,2022-06-21 16:01:53+00:00,1539277436684222465,"@beautifulgalles Hi there, we would really lik...",UPS_Canada,0,0
9998,2022-06-21 15:26:51+00:00,1539268617640058881,This is what happens when 95% of Canada's Civi...,JerryKovacs,0,0